{
 "title": "Subway2",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Simulation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Day of Week",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(voltdbbl_subway_time{STAT_LABEL_1=\"dayofweek\"})"
    }
   ]
  },
  {
   "title": "Hour",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltdbbl_subway_time{STAT_LABEL_1=\"hour\"}"
    }
   ]
  },
  {
   "title": "Minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "voltdbbl_subway_time{STAT_LABEL_1=\"minute\"}"
    }
   ]
  },
  {
   "title": "Time Speedup",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "voltdbbl_speed" }
   ]
  },
  {
   "title": "Target TPS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "voltdbbl_tps" }
   ]
  },
  {
   "title": "Busy Start Stations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "voltdbbl_busy_startingstations > 50",
     "legendFormat": "{{STAT_LABEL_2}}"
    }
   ]
  },
  {
   "title": "Busy Ending Stations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "avg by (STAT_LABEL_1)  (voltdbbl_busy_endingstations) > 50",
     "legendFormat": "{{STAT_LABEL_1}}"
    }
   ]
  },
  {
   "title": "Current Spending and credit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "targets": [
    {
     "expr": "avg by (STAT_LABEL_1)  (voltdbbl_subway_totals{STAT_LABEL_1=\"purchases_per_minute\"})/100",
     "legendFormat": "{{STAT_LABEL_1}}"
    },
    {
     "expr": "avg by (STAT_LABEL_1)  (voltdbbl_subway_totals{STAT_LABEL_1=\"spending_per_minute\"})/100",
     "legendFormat": "{{STAT_LABEL_1}}"
    }
   ]
  },
  {
   "title": "Activity by subsystem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "avg by (STAT_LABEL_1)  (voltdbbl_subsystem)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Journey Start and End",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "avg by (STAT_LABEL_1)  (voltdbbl_subway_totals{STAT_LABEL_1!=\"purchases_per_minute\",STAT_LABEL_1!=\"spending_per_minute\",STAT_LABEL_1!=\"current_users\"}) > 0",
     "legendFormat": "{{STAT_LABEL_1}}"
    },
    { "expr": "voltdbbl_bus", "legendFormat": "{{STAT_LABEL_1}}" }
   ]
  },
  {
   "title": "Current Subway Riders",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "avg by (STAT_LABEL_1)  (voltdbbl_subway_totals{STAT_LABEL_1=\"current_users\"})",
     "legendFormat": "{{STAT_LABEL_1}}"
    }
   ]
  },
  {
   "title": "Subway Starts",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "avg by (STAT_LABEL_1,STAT_LABEL_2,LATITUDE,LONGITUDE)  (voltdbbl_busy_startingstations)> 0"
    },
    {
     "expr": "voltdbbl_busy_endingstations * -1 < 0",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Subway Ends",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "avg by (STAT_LABEL_1,STAT_LABEL_2,LATITUDE,LONGITUDE)  (voltdbbl_busy_endingstations) > 0",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Subway Starts",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 45 },
   "targets": [
    { "expr": "voltdbbl_busy_endingstations ", "legendFormat": "__auto" }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Client Latency for card swipes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (STAT_LABEL_1)  (voltdbbl_latency_client)",
     "legendFormat": "{{STAT_LABEL_1}}"
    }
   ]
  },
  {
   "title": "Server Latency for card swipes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg by (STAT_LABEL_1)  (voltdbbl_latency_server)",
     "legendFormat": "{{STAT_LABEL_1}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (STAT_LABEL_1)  (voltdb_cpu_usage_percent)",
     "legendFormat": "CPU "
    }
   ]
  },
  {
   "title": "VoltDB RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "  (max (voltdb_memory_rss_bytes) / max(node_memory_MemTotal_bytes))*100",
     "legendFormat": "RAM Use"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "irate(voltdbbl_procedureprofile{measuretype=\"invocations\"}[5m])",
     "legendFormat": "{{procedure}}"
    }
   ]
  },
  {
   "title": "Bus Routes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 78 },
   "targets": [
    {
     "expr": "avg by (STAT_LABEL_2)  (voltdbbl_busy_bus_routes) > 50",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bus Routes",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 18, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (STAT_LABEL_2)  (voltdbbl_busy_bus_routes) > 0",
     "legendFormat": "{{STAT_LABEL_1}}"
    }
   ]
  }
 ]
}